// One-shot MLBBDex fetcher: pulls portraits, icons, ALL skin splashes,
// difficulty ratings + live meta (win/ban/pick, tier) for our hero pool
// into public/images/dex/ and writes a manifest for src/data/imagery.ts.
//
//   npm run fetch-dex [-- --force]
//
// Re-run weekly to refresh the meta snapshot + new skins.
// Data & art: MLBBDex (wiki CC BY-SA) — credited in the site footer.
import { mkdirSync, existsSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "images", "dex");
const API = "https://mlbbdex.com/api/v1";
const UA = "EuphexSite/1.0 (esports fan site)";
const FORCE = process.argv.includes("--force") || process.argv.includes("force");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// our slug -> dex slug
const DEX_SLUG = {
  fanny: "fanny", ling: "ling", hayabusa: "hayabusa", joy: "joy",
  lancelot: "lancelot", aamon: "aamon", gusion: "gusion",
  valentina: "valentina", pharsa: "pharsa", yve: "yve",
  cecilion: "cecilion", luoyi: "luo-yi", aurora: "aurora",
  kagura: "kagura", nana: "nana", xavier: "xavier", hirara: "hirara",
  beatrix: "beatrix", claude: "claude", brody: "brody",
  melissa: "melissa", layla: "layla", lesley: "lesley",
  yuzhong: "yu-zhong", terizla: "terizla", paquito: "paquito",
  lapulapu: "lapu-lapu", badang: "badang", belerick: "belerick",
  benedetta: "benedetta", estes: "estes", franco: "franco", chou: "chou",
  khufra: "khufra", mathilda: "mathilda", atlas: "atlas",
  angela: "angela", johnson: "johnson", natalia: "natalia",
};

async function getJson(url) {
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error(`HTTP ${r.status}: ${url}`);
  return r.json();
}

async function download(url, dest) {
  const full = url.startsWith("http") ? url : `https://mlbbdex.com${url}`;
  for (let a = 0; a < 3; a++) {
    try {
      const r = await fetch(full, { headers: { "User-Agent": UA } });
      if (r.ok) {
        writeFileSync(dest, Buffer.from(await r.arrayBuffer()));
        return true;
      }
    } catch { /* retry */ }
    await sleep(400 * (a + 1));
  }
  return false;
}

mkdirSync(OUT, { recursive: true });

// meta snapshot (one call)
let meta = {};
let measuredAt = "";
try {
  const rk = await getJson(`${API}/rankings`);
  measuredAt = rk.data?.measuredAt ?? "";
  for (const h of rk.data?.heroes ?? []) {
    meta[h.slug] = { tier: h.tier, winRate: h.winRate, banRate: h.banRate, pickRate: h.pickRate };
  }
  console.log(`rankings: ${Object.keys(meta).length} heroes, measured ${measuredAt}`);
} catch (e) {
  console.log(`rankings unavailable: ${e.message}`);
}

const heroes = {};
let bytes = 0;
let n = 0;

for (const [ours, dex] of Object.entries(DEX_SLUG)) {
  n++;
  try {
    const { data } = await getJson(`${API}/heroes/${dex}`);
    const files = {};
    const jobs = [];
    const put = (relUrl, file) => {
      if (!relUrl || (!FORCE && existsSync(join(OUT, file)))) return null;
      files[file] = relUrl;
      return (async () => {
        if (await download(relUrl, join(OUT, file))) {
          bytes += statSync(join(OUT, file)).size;
          return true;
        }
        return false;
      })();
    };
    if (data.images?.portrait) jobs.push(put(data.images.portrait, `${ours}-portrait.webp`));
    if (data.images?.icon) jobs.push(put(data.images.icon, `${ours}-icon.webp`));
    const skins = [];
    for (const s of data.skins ?? []) {
      const img = data.images?.skins?.[String(s.id)];
      if (!img) continue;
      const file = `${ours}-skin-${s.id}.webp`;
      const dl = put(img, file);
      if (dl) jobs.push(dl);
      skins.push({ name: s.name, img: `images/dex/${file}` });
    }
    await Promise.all(jobs);
    const splash = skins.length ? skins[0].img : null;
    heroes[ours] = {
      portrait: `images/dex/${ours}-portrait.webp`,
      icon: `images/dex/${ours}-icon.webp`,
      splash,
      skins,
      difficulty: data.ratings?.difficulty ?? null,
      ...(meta[dex] ? { meta: meta[dex] } : {}),
    };
    console.log(`got ${ours} (${skins.length} skins)`);
  } catch (e) {
    console.log(`MISS ${ours}: ${e.message}`);
  }
  await sleep(120);
  if (n % 10 === 0) console.log(`…${n}/${Object.keys(DEX_SLUG).length}`);
}

writeFileSync(
  join(ROOT, "src", "data", "dex.generated.ts"),
  `// AUTO-GENERATED by scripts/fetch-dex-art.mjs — do not edit by hand.\n// Data & art: MLBBDex (wiki CC BY-SA). Meta snapshot: ${measuredAt}\n` +
  `export const DEX_META_AT = ${JSON.stringify(measuredAt)};\n` +
  `export interface DexHero { portrait: string; icon: string; splash: string | null; skins: { name: string; img: string }[]; difficulty: number | null; meta?: { tier: string; winRate: number; banRate: number; pickRate: number } }\n` +
  `export const DEX_HEROES: Record<string, DexHero> = ${JSON.stringify(heroes, null, 2)};\n`,
);
console.log(`\nDone: ${Object.keys(heroes).length}/${Object.keys(DEX_SLUG).length} heroes, ${(bytes / 1048576).toFixed(1)} MB new.`);
