// AUTO-GENERATED by scripts/fetch-dex-art.mjs — do not edit by hand.
// Data & art: MLBBDex (wiki CC BY-SA). Meta snapshot: 2026-09-21T10:00:42.336Z
export const DEX_META_AT = "2026-09-21T10:00:42.336Z";
export interface DexHero { portrait: string; icon: string; splash: string | null; skins: { name: string; img: string }[]; difficulty: number | null; meta?: { tier: string; winRate: number; banRate: number; pickRate: number } }
export const DEX_HEROES: Record<string, DexHero> = {
  "fanny": {
    "portrait": "images/dex/fanny-portrait.webp",
    "icon": "images/dex/fanny-icon.webp",
    "splash": "images/dex/fanny-skin-101710.webp",
    "skins": [
      {
        "name": "Blade of Kibou",
        "img": "images/dex/fanny-skin-101710.webp"
      },
      {
        "name": "Heart Afloat",
        "img": "images/dex/fanny-skin-101711.webp"
      },
      {
        "name": "Mikasa",
        "img": "images/dex/fanny-skin-101712.webp"
      },
      {
        "name": "Blade Dancer",
        "img": "images/dex/fanny-skin-171.webp"
      },
      {
        "name": "Campus Youth",
        "img": "images/dex/fanny-skin-172.webp"
      },
      {
        "name": "Punk Princess",
        "img": "images/dex/fanny-skin-173.webp"
      },
      {
        "name": "Skylark",
        "img": "images/dex/fanny-skin-174.webp"
      },
      {
        "name": "Royal Cavalry",
        "img": "images/dex/fanny-skin-175.webp"
      },
      {
        "name": "Lifeguard",
        "img": "images/dex/fanny-skin-176.webp"
      },
      {
        "name": "Lightborn - Ranger",
        "img": "images/dex/fanny-skin-177.webp"
      },
      {
        "name": "Christmas Carnival",
        "img": "images/dex/fanny-skin-178.webp"
      },
      {
        "name": "Imperial Warrior",
        "img": "images/dex/fanny-skin-179.webp"
      }
    ],
    "difficulty": 10,
    "meta": {
      "tier": "C",
      "winRate": 43.01,
      "banRate": 1.83,
      "pickRate": 0.64
    }
  },
  "ling": {
    "portrait": "images/dex/ling-portrait.webp",
    "icon": "images/dex/ling-icon.webp",
    "splash": "images/dex/ling-skin-108410.webp",
    "skins": [
      {
        "name": "Neobeast Ling",
        "img": "images/dex/ling-skin-108410.webp"
      },
      {
        "name": "Cyan Finch",
        "img": "images/dex/ling-skin-841.webp"
      },
      {
        "name": "Fiery Dance",
        "img": "images/dex/ling-skin-842.webp"
      },
      {
        "name": "Street Punk",
        "img": "images/dex/ling-skin-843.webp"
      },
      {
        "name": "Night Shade",
        "img": "images/dex/ling-skin-844.webp"
      },
      {
        "name": "Cosmo Guard",
        "img": "images/dex/ling-skin-845.webp"
      },
      {
        "name": "Serene Plume",
        "img": "images/dex/ling-skin-846.webp"
      },
      {
        "name": "M-World Ling",
        "img": "images/dex/ling-skin-847.webp"
      },
      {
        "name": "Lord Shen",
        "img": "images/dex/ling-skin-848.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "S",
      "winRate": 53.25,
      "banRate": 0.94,
      "pickRate": 0.76
    }
  },
  "hayabusa": {
    "portrait": "images/dex/hayabusa-portrait.webp",
    "icon": "images/dex/hayabusa-icon.webp",
    "splash": "images/dex/hayabusa-skin-102110.webp",
    "skins": [
      {
        "name": "Exorcist Hayabusa",
        "img": "images/dex/hayabusa-skin-102110.webp"
      },
      {
        "name": "Kakashi Hatake",
        "img": "images/dex/hayabusa-skin-102111.webp"
      },
      {
        "name": "Crimson Shadow",
        "img": "images/dex/hayabusa-skin-211.webp"
      },
      {
        "name": "Spacetime Shadow",
        "img": "images/dex/hayabusa-skin-212.webp"
      },
      {
        "name": "Future Enforcer",
        "img": "images/dex/hayabusa-skin-213.webp"
      },
      {
        "name": "Sushi Master",
        "img": "images/dex/hayabusa-skin-214.webp"
      },
      {
        "name": "Experiment 21",
        "img": "images/dex/hayabusa-skin-215.webp"
      },
      {
        "name": "Shadow of Obscurity",
        "img": "images/dex/hayabusa-skin-216.webp"
      },
      {
        "name": "Biological Weapon",
        "img": "images/dex/hayabusa-skin-217.webp"
      },
      {
        "name": "Shura",
        "img": "images/dex/hayabusa-skin-218.webp"
      },
      {
        "name": "Techie Ninja",
        "img": "images/dex/hayabusa-skin-219.webp"
      }
    ],
    "difficulty": 6,
    "meta": {
      "tier": "B",
      "winRate": 48.83,
      "banRate": 2.65,
      "pickRate": 0.79
    }
  },
  "joy": {
    "portrait": "images/dex/joy-portrait.webp",
    "icon": "images/dex/joy-icon.webp",
    "splash": "images/dex/joy-skin-1181.webp",
    "skins": [
      {
        "name": "Flash of Miracle",
        "img": "images/dex/joy-skin-1181.webp"
      },
      {
        "name": "Feline Ranger",
        "img": "images/dex/joy-skin-1182.webp"
      },
      {
        "name": "Royal Protector",
        "img": "images/dex/joy-skin-1184.webp"
      },
      {
        "name": "Exostar Scout",
        "img": "images/dex/joy-skin-1185.webp"
      }
    ],
    "difficulty": 9,
    "meta": {
      "tier": "B",
      "winRate": 50.05,
      "banRate": 0.18,
      "pickRate": 0.14
    }
  },
  "lancelot": {
    "portrait": "images/dex/lancelot-portrait.webp",
    "icon": "images/dex/lancelot-icon.webp",
    "splash": "images/dex/lancelot-skin-104710.webp",
    "skins": [
      {
        "name": "Empyrean Flame",
        "img": "images/dex/lancelot-skin-104710.webp"
      },
      {
        "name": "Marques of Blades",
        "img": "images/dex/lancelot-skin-104711.webp"
      },
      {
        "name": "Guardian of the Shrine",
        "img": "images/dex/lancelot-skin-104712.webp"
      },
      {
        "name": "Blade of Roses",
        "img": "images/dex/lancelot-skin-471.webp"
      },
      {
        "name": "Masked Knight",
        "img": "images/dex/lancelot-skin-472.webp"
      },
      {
        "name": "Christmas Carnival",
        "img": "images/dex/lancelot-skin-473.webp"
      },
      {
        "name": "Royal Matador",
        "img": "images/dex/lancelot-skin-474.webp"
      },
      {
        "name": "Dark Earl",
        "img": "images/dex/lancelot-skin-475.webp"
      },
      {
        "name": "Pisces",
        "img": "images/dex/lancelot-skin-476.webp"
      },
      {
        "name": "Floral Knight",
        "img": "images/dex/lancelot-skin-477.webp"
      },
      {
        "name": "Swordmaster",
        "img": "images/dex/lancelot-skin-478.webp"
      },
      {
        "name": "Bren Esports",
        "img": "images/dex/lancelot-skin-479.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "C",
      "winRate": 43.15,
      "banRate": 0.44,
      "pickRate": 0.54
    }
  },
  "aamon": {
    "portrait": "images/dex/aamon-portrait.webp",
    "icon": "images/dex/aamon-icon.webp",
    "splash": "images/dex/aamon-skin-1091.webp",
    "skins": [
      {
        "name": "Duke of Shards",
        "img": "images/dex/aamon-skin-1091.webp"
      },
      {
        "name": "Night's Edge",
        "img": "images/dex/aamon-skin-1092.webp"
      },
      {
        "name": "Noble Crest",
        "img": "images/dex/aamon-skin-1093.webp"
      },
      {
        "name": "Cyber Assassin",
        "img": "images/dex/aamon-skin-1094.webp"
      },
      {
        "name": "Vessel of Deceit",
        "img": "images/dex/aamon-skin-1095.webp"
      }
    ],
    "difficulty": 6,
    "meta": {
      "tier": "B",
      "winRate": 49.75,
      "banRate": 2.27,
      "pickRate": 0.67
    }
  },
  "gusion": {
    "portrait": "images/dex/gusion-portrait.webp",
    "icon": "images/dex/gusion-icon.webp",
    "splash": "images/dex/gusion-skin-105610.webp",
    "skins": [
      {
        "name": "Soul Revelation",
        "img": "images/dex/gusion-skin-105610.webp"
      },
      {
        "name": "Dimension Walker",
        "img": "images/dex/gusion-skin-105611.webp"
      },
      {
        "name": "Desert Spider",
        "img": "images/dex/gusion-skin-105613.webp"
      },
      {
        "name": "Holy Blade",
        "img": "images/dex/gusion-skin-561.webp"
      },
      {
        "name": "Moonlight Sonata",
        "img": "images/dex/gusion-skin-562.webp"
      },
      {
        "name": "Hairstylist",
        "img": "images/dex/gusion-skin-563.webp"
      },
      {
        "name": "Cyber Ops",
        "img": "images/dex/gusion-skin-564.webp"
      },
      {
        "name": "Dangerous Liaison",
        "img": "images/dex/gusion-skin-565.webp"
      },
      {
        "name": "V.E.N.O.M. Emperor Scorpion",
        "img": "images/dex/gusion-skin-566.webp"
      },
      {
        "name": "K'",
        "img": "images/dex/gusion-skin-567.webp"
      },
      {
        "name": "Cosmic Gleam",
        "img": "images/dex/gusion-skin-568.webp"
      },
      {
        "name": "Night Owl",
        "img": "images/dex/gusion-skin-569.webp"
      }
    ],
    "difficulty": 8,
    "meta": {
      "tier": "B",
      "winRate": 48.08,
      "banRate": 3.97,
      "pickRate": 1.44
    }
  },
  "valentina": {
    "portrait": "images/dex/valentina-portrait.webp",
    "icon": "images/dex/valentina-icon.webp",
    "splash": "images/dex/valentina-skin-1101.webp",
    "skins": [
      {
        "name": "Prophetess of the Night",
        "img": "images/dex/valentina-skin-1101.webp"
      },
      {
        "name": "Twilight Charmer",
        "img": "images/dex/valentina-skin-1102.webp"
      },
      {
        "name": "Archmagister",
        "img": "images/dex/valentina-skin-1103.webp"
      },
      {
        "name": "Cyber Agent",
        "img": "images/dex/valentina-skin-1104.webp"
      },
      {
        "name": "Celestial Judicator",
        "img": "images/dex/valentina-skin-1105.webp"
      },
      {
        "name": "Dark Nexus",
        "img": "images/dex/valentina-skin-1106.webp"
      }
    ],
    "difficulty": 8,
    "meta": {
      "tier": "C",
      "winRate": 45.15,
      "banRate": 0.13,
      "pickRate": 0.16
    }
  },
  "pharsa": {
    "portrait": "images/dex/pharsa-portrait.webp",
    "icon": "images/dex/pharsa-icon.webp",
    "splash": "images/dex/pharsa-skin-105210.webp",
    "skins": [
      {
        "name": "Neon Shingetsu",
        "img": "images/dex/pharsa-skin-105210.webp"
      },
      {
        "name": "Neobeast Pharsa",
        "img": "images/dex/pharsa-skin-105211.webp"
      },
      {
        "name": "Wings of Vengeance",
        "img": "images/dex/pharsa-skin-521.webp"
      },
      {
        "name": "Wings of Heaven",
        "img": "images/dex/pharsa-skin-522.webp"
      },
      {
        "name": "Peafowl's Dance",
        "img": "images/dex/pharsa-skin-523.webp"
      },
      {
        "name": "Indigo Aviatrix",
        "img": "images/dex/pharsa-skin-524.webp"
      },
      {
        "name": "Enchanting Witch",
        "img": "images/dex/pharsa-skin-525.webp"
      },
      {
        "name": "Empress Phoenix",
        "img": "images/dex/pharsa-skin-526.webp"
      },
      {
        "name": "Samba Muse",
        "img": "images/dex/pharsa-skin-527.webp"
      },
      {
        "name": "Peony Bloom",
        "img": "images/dex/pharsa-skin-528.webp"
      },
      {
        "name": "Hierophant",
        "img": "images/dex/pharsa-skin-529.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "C",
      "winRate": 47.13,
      "banRate": 0.18,
      "pickRate": 0.37
    }
  },
  "yve": {
    "portrait": "images/dex/yve-portrait.webp",
    "icon": "images/dex/yve-icon.webp",
    "splash": "images/dex/yve-skin-1011.webp",
    "skins": [
      {
        "name": "Astrowarden",
        "img": "images/dex/yve-skin-1011.webp"
      },
      {
        "name": "Forest Hymn",
        "img": "images/dex/yve-skin-1012.webp"
      },
      {
        "name": "Ruin Protectress",
        "img": "images/dex/yve-skin-1013.webp"
      },
      {
        "name": "Flame Lotus",
        "img": "images/dex/yve-skin-1014.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "A",
      "winRate": 52.09,
      "banRate": 0.04,
      "pickRate": 0.05
    }
  },
  "cecilion": {
    "portrait": "images/dex/cecilion-portrait.webp",
    "icon": "images/dex/cecilion-icon.webp",
    "splash": "images/dex/cecilion-skin-911.webp",
    "skins": [
      {
        "name": "Embrace of Night",
        "img": "images/dex/cecilion-skin-911.webp"
      },
      {
        "name": "Wisteria Count",
        "img": "images/dex/cecilion-skin-912.webp"
      },
      {
        "name": "The Illusionist",
        "img": "images/dex/cecilion-skin-913.webp"
      },
      {
        "name": "Phantom Count",
        "img": "images/dex/cecilion-skin-914.webp"
      },
      {
        "name": "Stargazer",
        "img": "images/dex/cecilion-skin-915.webp"
      },
      {
        "name": "Crimson Wings",
        "img": "images/dex/cecilion-skin-916.webp"
      },
      {
        "name": "Hisoka",
        "img": "images/dex/cecilion-skin-917.webp"
      }
    ],
    "difficulty": 4,
    "meta": {
      "tier": "B",
      "winRate": 50.26,
      "banRate": 0.11,
      "pickRate": 0.57
    }
  },
  "luoyi": {
    "portrait": "images/dex/luoyi-portrait.webp",
    "icon": "images/dex/luoyi-icon.webp",
    "splash": "images/dex/luoyi-skin-961.webp",
    "skins": [
      {
        "name": "Yin-yang Geomancer",
        "img": "images/dex/luoyi-skin-961.webp"
      },
      {
        "name": "Yin-yang Mage",
        "img": "images/dex/luoyi-skin-962.webp"
      },
      {
        "name": "Tenko",
        "img": "images/dex/luoyi-skin-963.webp"
      },
      {
        "name": "Dawning Fortune",
        "img": "images/dex/luoyi-skin-964.webp"
      },
      {
        "name": "Siren Priestess",
        "img": "images/dex/luoyi-skin-965.webp"
      },
      {
        "name": "Elysium Guardian",
        "img": "images/dex/luoyi-skin-966.webp"
      },
      {
        "name": "Oracle of Sol",
        "img": "images/dex/luoyi-skin-967.webp"
      },
      {
        "name": "Starborne Matron",
        "img": "images/dex/luoyi-skin-968.webp"
      }
    ],
    "difficulty": 8,
    "meta": {
      "tier": "C",
      "winRate": 47.8,
      "banRate": 0.16,
      "pickRate": 0.28
    }
  },
  "aurora": {
    "portrait": "images/dex/aurora-portrait.webp",
    "icon": "images/dex/aurora-icon.webp",
    "splash": "images/dex/aurora-skin-361.webp",
    "skins": [
      {
        "name": "Maiden of the Glacier",
        "img": "images/dex/aurora-skin-361.webp"
      },
      {
        "name": "Nature's Throne",
        "img": "images/dex/aurora-skin-362.webp"
      },
      {
        "name": "Heartbreak Empress",
        "img": "images/dex/aurora-skin-363.webp"
      },
      {
        "name": "Foxy Lady",
        "img": "images/dex/aurora-skin-364.webp"
      },
      {
        "name": "Aquarius",
        "img": "images/dex/aurora-skin-365.webp"
      },
      {
        "name": "Kula Diamond",
        "img": "images/dex/aurora-skin-366.webp"
      },
      {
        "name": "Veil of the Celestials",
        "img": "images/dex/aurora-skin-367.webp"
      }
    ],
    "difficulty": 1,
    "meta": {
      "tier": "B",
      "winRate": 48.01,
      "banRate": 0.34,
      "pickRate": 0.59
    }
  },
  "kagura": {
    "portrait": "images/dex/kagura-portrait.webp",
    "icon": "images/dex/kagura-icon.webp",
    "splash": "images/dex/kagura-skin-102510.webp",
    "skins": [
      {
        "name": "Jade Blossom",
        "img": "images/dex/kagura-skin-102510.webp"
      },
      {
        "name": "Onmyouji Master",
        "img": "images/dex/kagura-skin-251.webp"
      },
      {
        "name": "Flower Season",
        "img": "images/dex/kagura-skin-252.webp"
      },
      {
        "name": "Cherry Witch",
        "img": "images/dex/kagura-skin-253.webp"
      },
      {
        "name": "Summer Festival",
        "img": "images/dex/kagura-skin-254.webp"
      },
      {
        "name": "Dragon Maiden",
        "img": "images/dex/kagura-skin-255.webp"
      },
      {
        "name": "Rainy Walk",
        "img": "images/dex/kagura-skin-256.webp"
      },
      {
        "name": "Water Lily",
        "img": "images/dex/kagura-skin-257.webp"
      },
      {
        "name": "Exorcist Kagura",
        "img": "images/dex/kagura-skin-258.webp"
      },
      {
        "name": "Beyond the Clouds Kagura",
        "img": "images/dex/kagura-skin-259.webp"
      }
    ],
    "difficulty": 9,
    "meta": {
      "tier": "A",
      "winRate": 52.45,
      "banRate": 1.47,
      "pickRate": 0.88
    }
  },
  "nana": {
    "portrait": "images/dex/nana-portrait.webp",
    "icon": "images/dex/nana-icon.webp",
    "splash": "images/dex/nana-skin-051.webp",
    "skins": [
      {
        "name": "Sweet Leonin",
        "img": "images/dex/nana-skin-051.webp"
      },
      {
        "name": "Clockwork Maid",
        "img": "images/dex/nana-skin-052.webp"
      },
      {
        "name": "Graveyard Party",
        "img": "images/dex/nana-skin-053.webp"
      },
      {
        "name": "Slumber Party",
        "img": "images/dex/nana-skin-054.webp"
      },
      {
        "name": "Wind Fairy",
        "img": "images/dex/nana-skin-055.webp"
      },
      {
        "name": "Mecha Baby",
        "img": "images/dex/nana-skin-056.webp"
      },
      {
        "name": "Sundress",
        "img": "images/dex/nana-skin-057.webp"
      },
      {
        "name": "Aqua Pura",
        "img": "images/dex/nana-skin-058.webp"
      },
      {
        "name": "Cyclone Clash",
        "img": "images/dex/nana-skin-059.webp"
      },
      {
        "name": "Mistbender Nana",
        "img": "images/dex/nana-skin-100510.webp"
      }
    ],
    "difficulty": null,
    "meta": {
      "tier": "C",
      "winRate": 46.55,
      "banRate": 2.93,
      "pickRate": 1.59
    }
  },
  "xavier": {
    "portrait": "images/dex/xavier-portrait.webp",
    "icon": "images/dex/xavier-icon.webp",
    "splash": "images/dex/xavier-skin-1151.webp",
    "skins": [
      {
        "name": "Defier of Light",
        "img": "images/dex/xavier-skin-1151.webp"
      },
      {
        "name": "Verdict of Light",
        "img": "images/dex/xavier-skin-1152.webp"
      },
      {
        "name": "Satoru Gojo",
        "img": "images/dex/xavier-skin-1153.webp"
      },
      {
        "name": "Hardlight Artificer",
        "img": "images/dex/xavier-skin-1154.webp"
      },
      {
        "name": "Beyond the Clouds Xavier",
        "img": "images/dex/xavier-skin-1155.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "B",
      "winRate": 50.17,
      "banRate": 0.12,
      "pickRate": 0.58
    }
  },
  "hirara": {
    "portrait": "images/dex/hirara-portrait.webp",
    "icon": "images/dex/hirara-icon.webp",
    "splash": "images/dex/hirara-skin-1331.webp",
    "skins": [
      {
        "name": "Fallen Scarlet",
        "img": "images/dex/hirara-skin-1331.webp"
      },
      {
        "name": "Gilded Embers",
        "img": "images/dex/hirara-skin-1332.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "S+",
      "winRate": 55.06,
      "banRate": 59.4,
      "pickRate": 0.78
    }
  },
  "beatrix": {
    "portrait": "images/dex/beatrix-portrait.webp",
    "icon": "images/dex/beatrix-icon.webp",
    "splash": "images/dex/beatrix-skin-1051.webp",
    "skins": [
      {
        "name": "Dawnbreak Soldier",
        "img": "images/dex/beatrix-skin-1051.webp"
      },
      {
        "name": "X Factor",
        "img": "images/dex/beatrix-skin-1052.webp"
      },
      {
        "name": "Blitz Attack",
        "img": "images/dex/beatrix-skin-1053.webp"
      },
      {
        "name": "Space Agent",
        "img": "images/dex/beatrix-skin-1054.webp"
      },
      {
        "name": "Light Chaser",
        "img": "images/dex/beatrix-skin-1055.webp"
      },
      {
        "name": "Stellar Briliance",
        "img": "images/dex/beatrix-skin-1056.webp"
      },
      {
        "name": "Vibrant Fiesta",
        "img": "images/dex/beatrix-skin-1057.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "A",
      "winRate": 52.17,
      "banRate": 0.44,
      "pickRate": 0.72
    }
  },
  "claude": {
    "portrait": "images/dex/claude-portrait.webp",
    "icon": "images/dex/claude-icon.webp",
    "splash": "images/dex/claude-skin-106510.webp",
    "skins": [
      {
        "name": "Heart Aflame",
        "img": "images/dex/claude-skin-106510.webp"
      },
      {
        "name": "Challenger's Spark",
        "img": "images/dex/claude-skin-106511.webp"
      },
      {
        "name": "Cosmic Blaze",
        "img": "images/dex/claude-skin-106512.webp"
      },
      {
        "name": "Master Thief",
        "img": "images/dex/claude-skin-651.webp"
      },
      {
        "name": "Golden Bullet",
        "img": "images/dex/claude-skin-652.webp"
      },
      {
        "name": "Plunderous Pirate",
        "img": "images/dex/claude-skin-653.webp"
      },
      {
        "name": "Mecha Dragon",
        "img": "images/dex/claude-skin-654.webp"
      },
      {
        "name": "Lifeguard",
        "img": "images/dex/claude-skin-655.webp"
      },
      {
        "name": "Christmas Carnival",
        "img": "images/dex/claude-skin-656.webp"
      },
      {
        "name": "Earth's Mightiest",
        "img": "images/dex/claude-skin-657.webp"
      },
      {
        "name": "Blazing Trace",
        "img": "images/dex/claude-skin-658.webp"
      },
      {
        "name": "Bad Bro",
        "img": "images/dex/claude-skin-659.webp"
      }
    ],
    "difficulty": 6,
    "meta": {
      "tier": "B",
      "winRate": 48.82,
      "banRate": 0.21,
      "pickRate": 0.76
    }
  },
  "brody": {
    "portrait": "images/dex/brody-portrait.webp",
    "icon": "images/dex/brody-icon.webp",
    "splash": "images/dex/brody-skin-1001.webp",
    "skins": [
      {
        "name": "The Lone Star",
        "img": "images/dex/brody-skin-1001.webp"
      },
      {
        "name": "Nameless Stray",
        "img": "images/dex/brody-skin-1002.webp"
      },
      {
        "name": "S.T.U.N. Brody",
        "img": "images/dex/brody-skin-1003.webp"
      },
      {
        "name": "Lethal Fang",
        "img": "images/dex/brody-skin-1004.webp"
      },
      {
        "name": "Ore-chemist",
        "img": "images/dex/brody-skin-1005.webp"
      },
      {
        "name": "Quantum Grip",
        "img": "images/dex/brody-skin-1006.webp"
      },
      {
        "name": "APBren",
        "img": "images/dex/brody-skin-1007.webp"
      },
      {
        "name": "Neobeast Brody",
        "img": "images/dex/brody-skin-1008.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "A",
      "winRate": 51.08,
      "banRate": 2.6,
      "pickRate": 1.23
    }
  },
  "melissa": {
    "portrait": "images/dex/melissa-portrait.webp",
    "icon": "images/dex/melissa-icon.webp",
    "splash": "images/dex/melissa-skin-1141.webp",
    "skins": [
      {
        "name": "Cursed Needle",
        "img": "images/dex/melissa-skin-1141.webp"
      },
      {
        "name": "Twinge Weaver",
        "img": "images/dex/melissa-skin-1142.webp"
      },
      {
        "name": "Nobara Kugisaki",
        "img": "images/dex/melissa-skin-1143.webp"
      },
      {
        "name": "Nightwalker",
        "img": "images/dex/melissa-skin-1144.webp"
      },
      {
        "name": "SPARKLE Melissa",
        "img": "images/dex/melissa-skin-1145.webp"
      },
      {
        "name": "Umbra Bloom",
        "img": "images/dex/melissa-skin-1146.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "A",
      "winRate": 49.31,
      "banRate": 5.32,
      "pickRate": 0.77
    }
  },
  "layla": {
    "portrait": "images/dex/layla-portrait.webp",
    "icon": "images/dex/layla-icon.webp",
    "splash": "images/dex/layla-skin-101810.webp",
    "skins": [
      {
        "name": "Twilight Waltz",
        "img": "images/dex/layla-skin-101810.webp"
      },
      {
        "name": "Paranormal Operative",
        "img": "images/dex/layla-skin-101811.webp"
      },
      {
        "name": "Energy Gunner",
        "img": "images/dex/layla-skin-181.webp"
      },
      {
        "name": "Green Flash",
        "img": "images/dex/layla-skin-182.webp"
      },
      {
        "name": "Bunny Babe",
        "img": "images/dex/layla-skin-183.webp"
      },
      {
        "name": "Cannon and Roses",
        "img": "images/dex/layla-skin-184.webp"
      },
      {
        "name": "Blue Spectre",
        "img": "images/dex/layla-skin-185.webp"
      },
      {
        "name": "Classic Malefic Gunner",
        "img": "images/dex/layla-skin-186.webp"
      },
      {
        "name": "S.A.B.E.R. Breacher",
        "img": "images/dex/layla-skin-187.webp"
      },
      {
        "name": "Blazing Gun",
        "img": "images/dex/layla-skin-188.webp"
      },
      {
        "name": "Miss Hikari",
        "img": "images/dex/layla-skin-189.webp"
      }
    ],
    "difficulty": 2,
    "meta": {
      "tier": "B",
      "winRate": 47.98,
      "banRate": 0.81,
      "pickRate": 1.03
    }
  },
  "lesley": {
    "portrait": "images/dex/lesley-portrait.webp",
    "icon": "images/dex/lesley-icon.webp",
    "splash": "images/dex/lesley-skin-105310.webp",
    "skins": [
      {
        "name": "Hawk-eyed Sniper",
        "img": "images/dex/lesley-skin-105310.webp"
      },
      {
        "name": "Deadeye Spectre",
        "img": "images/dex/lesley-skin-105311.webp"
      },
      {
        "name": "Meowkin Hunter",
        "img": "images/dex/lesley-skin-105312.webp"
      },
      {
        "name": "Duchess of Tides",
        "img": "images/dex/lesley-skin-105313.webp"
      },
      {
        "name": "Deadly Sniper",
        "img": "images/dex/lesley-skin-531.webp"
      },
      {
        "name": "Royal Musketeer",
        "img": "images/dex/lesley-skin-532.webp"
      },
      {
        "name": "General Rosa",
        "img": "images/dex/lesley-skin-533.webp"
      },
      {
        "name": "Cheergunner",
        "img": "images/dex/lesley-skin-534.webp"
      },
      {
        "name": "Stellaris Ghost",
        "img": "images/dex/lesley-skin-535.webp"
      },
      {
        "name": "Dangerous Love",
        "img": "images/dex/lesley-skin-536.webp"
      },
      {
        "name": "Angelic Agent",
        "img": "images/dex/lesley-skin-537.webp"
      },
      {
        "name": "Lethal Lady",
        "img": "images/dex/lesley-skin-538.webp"
      },
      {
        "name": "Falcon Mistress",
        "img": "images/dex/lesley-skin-539.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "B",
      "winRate": 48.06,
      "banRate": 6.54,
      "pickRate": 1.78
    }
  },
  "yuzhong": {
    "portrait": "images/dex/yuzhong-portrait.webp",
    "icon": "images/dex/yuzhong-icon.webp",
    "splash": "images/dex/yuzhong-skin-951.webp",
    "skins": [
      {
        "name": "Black Dragon",
        "img": "images/dex/yuzhong-skin-951.webp"
      },
      {
        "name": "Emerald Dragon",
        "img": "images/dex/yuzhong-skin-952.webp"
      },
      {
        "name": "Biohazard",
        "img": "images/dex/yuzhong-skin-953.webp"
      },
      {
        "name": "Blood Serpent",
        "img": "images/dex/yuzhong-skin-954.webp"
      },
      {
        "name": "Exorcist Yu Zhong",
        "img": "images/dex/yuzhong-skin-955.webp"
      },
      {
        "name": "Dragon's Shade",
        "img": "images/dex/yuzhong-skin-957.webp"
      },
      {
        "name": "Cosmic Dragon",
        "img": "images/dex/yuzhong-skin-958.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "B",
      "winRate": 49.48,
      "banRate": 0.7,
      "pickRate": 0.55
    }
  },
  "terizla": {
    "portrait": "images/dex/terizla-portrait.webp",
    "icon": "images/dex/terizla-icon.webp",
    "splash": "images/dex/terizla-skin-821.webp",
    "skins": [
      {
        "name": "Executioner",
        "img": "images/dex/terizla-skin-821.webp"
      },
      {
        "name": "Abyss Guard",
        "img": "images/dex/terizla-skin-822.webp"
      },
      {
        "name": "Flare",
        "img": "images/dex/terizla-skin-823.webp"
      },
      {
        "name": "Hammer Giant",
        "img": "images/dex/terizla-skin-824.webp"
      },
      {
        "name": "Rustwreck",
        "img": "images/dex/terizla-skin-825.webp"
      },
      {
        "name": "Flames of Judgement",
        "img": "images/dex/terizla-skin-826.webp"
      },
      {
        "name": "Soulblight Tyrant",
        "img": "images/dex/terizla-skin-827.webp"
      }
    ],
    "difficulty": 3,
    "meta": {
      "tier": "A",
      "winRate": 50.53,
      "banRate": 0.16,
      "pickRate": 0.32
    }
  },
  "paquito": {
    "portrait": "images/dex/paquito-portrait.webp",
    "icon": "images/dex/paquito-icon.webp",
    "splash": "images/dex/paquito-skin-1031.webp",
    "skins": [
      {
        "name": "The Heavenly Fist",
        "img": "images/dex/paquito-skin-1031.webp"
      },
      {
        "name": "Death Blow",
        "img": "images/dex/paquito-skin-1032.webp"
      },
      {
        "name": "Manny Pacquiao",
        "img": "images/dex/paquito-skin-1033.webp"
      },
      {
        "name": "Underground Boxer",
        "img": "images/dex/paquito-skin-1034.webp"
      },
      {
        "name": "Fulgent Punch",
        "img": "images/dex/paquito-skin-1035.webp"
      },
      {
        "name": "Fist of Light",
        "img": "images/dex/paquito-skin-1036.webp"
      },
      {
        "name": "Blazing Tiger",
        "img": "images/dex/paquito-skin-1037.webp"
      },
      {
        "name": "Terry Bogard",
        "img": "images/dex/paquito-skin-1038.webp"
      },
      {
        "name": "Fist of Glory",
        "img": "images/dex/paquito-skin-1039.webp"
      }
    ],
    "difficulty": 9,
    "meta": {
      "tier": "S+",
      "winRate": 51.07,
      "banRate": 46.92,
      "pickRate": 2.02
    }
  },
  "lapulapu": {
    "portrait": "images/dex/lapulapu-portrait.webp",
    "icon": "images/dex/lapulapu-icon.webp",
    "splash": "images/dex/lapulapu-skin-371.webp",
    "skins": [
      {
        "name": "Courageous Blade",
        "img": "images/dex/lapulapu-skin-371.webp"
      },
      {
        "name": "Ancestral Blade",
        "img": "images/dex/lapulapu-skin-372.webp"
      },
      {
        "name": "Imperial Champion",
        "img": "images/dex/lapulapu-skin-373.webp"
      },
      {
        "name": "Vulcan",
        "img": "images/dex/lapulapu-skin-374.webp"
      },
      {
        "name": "Special Force",
        "img": "images/dex/lapulapu-skin-375.webp"
      },
      {
        "name": "Son of the Wild",
        "img": "images/dex/lapulapu-skin-376.webp"
      },
      {
        "name": "Adlaw's Chosen",
        "img": "images/dex/lapulapu-skin-377.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "B",
      "winRate": 49.22,
      "banRate": 0.31,
      "pickRate": 0.33
    }
  },
  "badang": {
    "portrait": "images/dex/badang-portrait.webp",
    "icon": "images/dex/badang-icon.webp",
    "splash": "images/dex/badang-skin-771.webp",
    "skins": [
      {
        "name": "Tribal Warrior",
        "img": "images/dex/badang-skin-771.webp"
      },
      {
        "name": "Ironfists",
        "img": "images/dex/badang-skin-772.webp"
      },
      {
        "name": "Susanoo",
        "img": "images/dex/badang-skin-773.webp"
      },
      {
        "name": "Leo",
        "img": "images/dex/badang-skin-774.webp"
      },
      {
        "name": "Fist of Zen",
        "img": "images/dex/badang-skin-776.webp"
      },
      {
        "name": "Pegasus Seiya",
        "img": "images/dex/badang-skin-777.webp"
      },
      {
        "name": "Sagittarius Seiya",
        "img": "images/dex/badang-skin-778.webp"
      }
    ],
    "difficulty": 3,
    "meta": {
      "tier": "A",
      "winRate": 50.01,
      "banRate": 6.45,
      "pickRate": 1.76
    }
  },
  "belerick": {
    "portrait": "images/dex/belerick-portrait.webp",
    "icon": "images/dex/belerick-icon.webp",
    "splash": "images/dex/belerick-skin-701.webp",
    "skins": [
      {
        "name": "Guard of Nature",
        "img": "images/dex/belerick-skin-701.webp"
      },
      {
        "name": "Tiger's Claw",
        "img": "images/dex/belerick-skin-702.webp"
      },
      {
        "name": "Torch Guardian",
        "img": "images/dex/belerick-skin-703.webp"
      },
      {
        "name": "The Deep One",
        "img": "images/dex/belerick-skin-704.webp"
      },
      {
        "name": "Emerald Guardian",
        "img": "images/dex/belerick-skin-705.webp"
      },
      {
        "name": "Arbiter of Stars",
        "img": "images/dex/belerick-skin-706.webp"
      }
    ],
    "difficulty": 1,
    "meta": {
      "tier": "S+",
      "winRate": 52.92,
      "banRate": 49.35,
      "pickRate": 1.89
    }
  },
  "benedetta": {
    "portrait": "images/dex/benedetta-portrait.webp",
    "icon": "images/dex/benedetta-icon.webp",
    "splash": "images/dex/benedetta-skin-971.webp",
    "skins": [
      {
        "name": "Shadow Ranger",
        "img": "images/dex/benedetta-skin-971.webp"
      },
      {
        "name": "Honor Blade",
        "img": "images/dex/benedetta-skin-972.webp"
      },
      {
        "name": "Street Thrasher",
        "img": "images/dex/benedetta-skin-973.webp"
      },
      {
        "name": "Death Oath",
        "img": "images/dex/benedetta-skin-974.webp"
      },
      {
        "name": "Moonblade",
        "img": "images/dex/benedetta-skin-975.webp"
      },
      {
        "name": "Panigale V4S Rider",
        "img": "images/dex/benedetta-skin-976.webp"
      },
      {
        "name": "Quantum Edge",
        "img": "images/dex/benedetta-skin-977.webp"
      },
      {
        "name": "Phantom Mirage",
        "img": "images/dex/benedetta-skin-978.webp"
      }
    ],
    "difficulty": 8,
    "meta": {
      "tier": "S",
      "winRate": 53.34,
      "banRate": 0.27,
      "pickRate": 0.35
    }
  },
  "estes": {
    "portrait": "images/dex/estes-portrait.webp",
    "icon": "images/dex/estes-icon.webp",
    "splash": "images/dex/estes-skin-341.webp",
    "skins": [
      {
        "name": "Moon Elf King",
        "img": "images/dex/estes-skin-341.webp"
      },
      {
        "name": "Holy Priest",
        "img": "images/dex/estes-skin-342.webp"
      },
      {
        "name": "Galaxy Dominator",
        "img": "images/dex/estes-skin-343.webp"
      },
      {
        "name": "White Crane",
        "img": "images/dex/estes-skin-344.webp"
      },
      {
        "name": "Crow Bishop",
        "img": "images/dex/estes-skin-345.webp"
      },
      {
        "name": "Rattan Dragon",
        "img": "images/dex/estes-skin-346.webp"
      },
      {
        "name": "Blacklist International",
        "img": "images/dex/estes-skin-347.webp"
      },
      {
        "name": "Arcane Magistrate",
        "img": "images/dex/estes-skin-348.webp"
      },
      {
        "name": "SPARKLE Estes",
        "img": "images/dex/estes-skin-349.webp"
      }
    ],
    "difficulty": 3,
    "meta": {
      "tier": "S+",
      "winRate": 52.83,
      "banRate": 31.13,
      "pickRate": 0.72
    }
  },
  "franco": {
    "portrait": "images/dex/franco-portrait.webp",
    "icon": "images/dex/franco-icon.webp",
    "splash": "images/dex/franco-skin-101.webp",
    "skins": [
      {
        "name": "Frozen Warrior",
        "img": "images/dex/franco-skin-101.webp"
      },
      {
        "name": "Quantum Vanguard",
        "img": "images/dex/franco-skin-101010.webp"
      },
      {
        "name": "Masterchef",
        "img": "images/dex/franco-skin-102.webp"
      },
      {
        "name": "Apocalypse",
        "img": "images/dex/franco-skin-103.webp"
      },
      {
        "name": "Locomotive",
        "img": "images/dex/franco-skin-104.webp"
      },
      {
        "name": "Wheatfield Nightmare",
        "img": "images/dex/franco-skin-105.webp"
      },
      {
        "name": "Valhalla Ruler",
        "img": "images/dex/franco-skin-106.webp"
      },
      {
        "name": "Blazing Axe",
        "img": "images/dex/franco-skin-107.webp"
      },
      {
        "name": "Bone Crusher",
        "img": "images/dex/franco-skin-108.webp"
      },
      {
        "name": "King of Hell",
        "img": "images/dex/franco-skin-109.webp"
      }
    ],
    "difficulty": 2,
    "meta": {
      "tier": "C",
      "winRate": 41.5,
      "banRate": 2.89,
      "pickRate": 0.91
    }
  },
  "chou": {
    "portrait": "images/dex/chou-portrait.webp",
    "icon": "images/dex/chou-icon.webp",
    "splash": "images/dex/chou-skin-102610.webp",
    "skins": [
      {
        "name": "Dragon Shiryu",
        "img": "images/dex/chou-skin-102610.webp"
      },
      {
        "name": "Libra Shiryu",
        "img": "images/dex/chou-skin-102611.webp"
      },
      {
        "name": "ECHO",
        "img": "images/dex/chou-skin-102612.webp"
      },
      {
        "name": "Kung Fu Boy",
        "img": "images/dex/chou-skin-261.webp"
      },
      {
        "name": "Hip-hop Boy",
        "img": "images/dex/chou-skin-262.webp"
      },
      {
        "name": "Dragon Boy",
        "img": "images/dex/chou-skin-263.webp"
      },
      {
        "name": "King of Muay Thai",
        "img": "images/dex/chou-skin-264.webp"
      },
      {
        "name": "Furious Tiger",
        "img": "images/dex/chou-skin-265.webp"
      },
      {
        "name": "Iori Yagami",
        "img": "images/dex/chou-skin-266.webp"
      },
      {
        "name": "Go Ballistic",
        "img": "images/dex/chou-skin-267.webp"
      },
      {
        "name": "Thunderfist",
        "img": "images/dex/chou-skin-268.webp"
      },
      {
        "name": "S.T.U.N. Chou",
        "img": "images/dex/chou-skin-269.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "C",
      "winRate": 44.03,
      "banRate": 2.72,
      "pickRate": 1.16
    }
  },
  "khufra": {
    "portrait": "images/dex/khufra-portrait.webp",
    "icon": "images/dex/khufra-icon.webp",
    "splash": "images/dex/khufra-skin-781.webp",
    "skins": [
      {
        "name": "Desert Tyrant",
        "img": "images/dex/khufra-skin-781.webp"
      },
      {
        "name": "Desert Owl",
        "img": "images/dex/khufra-skin-782.webp"
      },
      {
        "name": "Apophis",
        "img": "images/dex/khufra-skin-783.webp"
      },
      {
        "name": "Gentleman Thief",
        "img": "images/dex/khufra-skin-784.webp"
      },
      {
        "name": "Volcanic Overlord",
        "img": "images/dex/khufra-skin-785.webp"
      },
      {
        "name": "Dreadful Clown",
        "img": "images/dex/khufra-skin-786.webp"
      },
      {
        "name": "Iron Hook",
        "img": "images/dex/khufra-skin-787.webp"
      },
      {
        "name": "Cursed Scroll",
        "img": "images/dex/khufra-skin-788.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "S+",
      "winRate": 55.99,
      "banRate": 1.42,
      "pickRate": 0.29
    }
  },
  "mathilda": {
    "portrait": "images/dex/mathilda-portrait.webp",
    "icon": "images/dex/mathilda-icon.webp",
    "splash": "images/dex/mathilda-skin-1021.webp",
    "skins": [
      {
        "name": "Swift Plume",
        "img": "images/dex/mathilda-skin-1021.webp"
      },
      {
        "name": "Unrestrained Delight",
        "img": "images/dex/mathilda-skin-1022.webp"
      },
      {
        "name": "Floral Crown",
        "img": "images/dex/mathilda-skin-1023.webp"
      },
      {
        "name": "Dream Groove",
        "img": "images/dex/mathilda-skin-1024.webp"
      },
      {
        "name": "Dreambound Pixie",
        "img": "images/dex/mathilda-skin-1026.webp"
      }
    ],
    "difficulty": 7,
    "meta": {
      "tier": "C",
      "winRate": 46.32,
      "banRate": 0.21,
      "pickRate": 0.17
    }
  },
  "atlas": {
    "portrait": "images/dex/atlas-portrait.webp",
    "icon": "images/dex/atlas-icon.webp",
    "splash": "images/dex/atlas-skin-931.webp",
    "skins": [
      {
        "name": "Ocean Gladiator",
        "img": "images/dex/atlas-skin-931.webp"
      },
      {
        "name": "Reactor Core",
        "img": "images/dex/atlas-skin-932.webp"
      },
      {
        "name": "Fuel Turbine",
        "img": "images/dex/atlas-skin-933.webp"
      },
      {
        "name": "Space Mech",
        "img": "images/dex/atlas-skin-934.webp"
      },
      {
        "name": "Rune of Sentinel",
        "img": "images/dex/atlas-skin-935.webp"
      },
      {
        "name": "Mecha Infernus",
        "img": "images/dex/atlas-skin-936.webp"
      }
    ],
    "difficulty": 5,
    "meta": {
      "tier": "S",
      "winRate": 52.56,
      "banRate": 11.23,
      "pickRate": 1.01
    }
  },
  "angela": {
    "portrait": "images/dex/angela-portrait.webp",
    "icon": "images/dex/angela-icon.webp",
    "splash": "images/dex/angela-skin-105510.webp",
    "skins": [
      {
        "name": "Avatar of Time",
        "img": "images/dex/angela-skin-105510.webp"
      },
      {
        "name": "Strings of Fate",
        "img": "images/dex/angela-skin-105511.webp"
      },
      {
        "name": "Bunnylove",
        "img": "images/dex/angela-skin-551.webp"
      },
      {
        "name": "Dove&Love",
        "img": "images/dex/angela-skin-552.webp"
      },
      {
        "name": "Shanghai Maiden",
        "img": "images/dex/angela-skin-553.webp"
      },
      {
        "name": "V.E.N.O.M. Vespid",
        "img": "images/dex/angela-skin-554.webp"
      },
      {
        "name": "Scream Doll",
        "img": "images/dex/angela-skin-555.webp"
      },
      {
        "name": "Summer Vibes",
        "img": "images/dex/angela-skin-556.webp"
      },
      {
        "name": "Floral Elf",
        "img": "images/dex/angela-skin-557.webp"
      },
      {
        "name": "Heartstring",
        "img": "images/dex/angela-skin-558.webp"
      },
      {
        "name": "Cyber Cherubin",
        "img": "images/dex/angela-skin-559.webp"
      }
    ],
    "difficulty": 6,
    "meta": {
      "tier": "A",
      "winRate": 49.85,
      "banRate": 6.75,
      "pickRate": 1.66
    }
  },
  "johnson": {
    "portrait": "images/dex/johnson-portrait.webp",
    "icon": "images/dex/johnson-icon.webp",
    "splash": "images/dex/johnson-skin-321.webp",
    "skins": [
      {
        "name": "Wild Engine",
        "img": "images/dex/johnson-skin-321.webp"
      },
      {
        "name": "Fire Chief",
        "img": "images/dex/johnson-skin-322.webp"
      },
      {
        "name": "S.A.B.E.R. Automata",
        "img": "images/dex/johnson-skin-323.webp"
      },
      {
        "name": "Jeepney Racer",
        "img": "images/dex/johnson-skin-324.webp"
      },
      {
        "name": "Wreck King",
        "img": "images/dex/johnson-skin-325.webp"
      },
      {
        "name": "Death Ride",
        "img": "images/dex/johnson-skin-326.webp"
      },
      {
        "name": "Optimus Prime",
        "img": "images/dex/johnson-skin-327.webp"
      },
      {
        "name": "Starblazer",
        "img": "images/dex/johnson-skin-328.webp"
      },
      {
        "name": "Sovereign of Realms",
        "img": "images/dex/johnson-skin-329.webp"
      }
    ],
    "difficulty": 6,
    "meta": {
      "tier": "B",
      "winRate": 47.85,
      "banRate": 1.57,
      "pickRate": 0.74
    }
  },
  "natalia": {
    "portrait": "images/dex/natalia-portrait.webp",
    "icon": "images/dex/natalia-icon.webp",
    "splash": "images/dex/natalia-skin-241.webp",
    "skins": [
      {
        "name": "Bright Claw",
        "img": "images/dex/natalia-skin-241.webp"
      },
      {
        "name": "Glass Blade",
        "img": "images/dex/natalia-skin-242.webp"
      },
      {
        "name": "Phantom Dancer",
        "img": "images/dex/natalia-skin-243.webp"
      },
      {
        "name": "Deadly Mamba",
        "img": "images/dex/natalia-skin-244.webp"
      },
      {
        "name": "Midnight Raven",
        "img": "images/dex/natalia-skin-245.webp"
      },
      {
        "name": "Grim Strangler",
        "img": "images/dex/natalia-skin-246.webp"
      },
      {
        "name": "Cyber Spectre",
        "img": "images/dex/natalia-skin-247.webp"
      },
      {
        "name": "Warrioress Paragon",
        "img": "images/dex/natalia-skin-248.webp"
      },
      {
        "name": "Soul Huntress",
        "img": "images/dex/natalia-skin-249.webp"
      }
    ],
    "difficulty": 9,
    "meta": {
      "tier": "A",
      "winRate": 50.24,
      "banRate": 1.24,
      "pickRate": 0.28
    }
  }
};
