// AUTO-GENERATED by scripts/fetch-hero-art.mjs — do not edit by hand.
// Official renders © Moonton (via MLBB Wiki).
export const OFFICIAL_HEROES = ["aamon","angela","atlas","badang","cecilion","chou","claude","estes","fanny","franco","gusion","hayabusa","khufra","lapulapu","lesley","ling","mathilda","nana","natalia","paquito","yuzhong","yve"] as const;
